name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Clean Up
      run: |
        rm -rf .env
        rm -rf .github

    - name: Create React App Directory
      run: |
        mkdir my-react-app
        cd my-react-app
        npx create-react-app .

    - name: Install react-frontend-template
      run: |
        cd my-react-app
        npm install react-frontend-template

    - name: Invoke react-frontend-template
      run: |
        cd my-react-app
        npx react-frontend-template -t ${{ secrets.TEMPLATE_NAME }}
